### ISSUE TITLE
Wrong link on CSRF resource

### ISSUE THREAD

**Issue by MaggieAppleton** [mikesherov/web-security-essentials#1]
The link to the OWASP Cross-Site Request Forgery (CSRF) page under the prerequisite learning material goes to a 404.
Currently goes here -> https://owasp.org/www-community/crsf

Looks like the original resource has been moved to here -> https://owasp.org/www-community/attacks/csrf

**Comment by mikesherov** [comment]
Fixed! Thanks Maggie!
